name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@v2"
      - name: my-step
        run: make say-hello
      
